name: Test
on:
  workflow_dispatch:
jobs:
  test_build_umh:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64
    - name: build
      run: |
        msbuild /m umh/capemon.sln /p:Configuration=Release /p:Platform=x64
